const mensagens = [
    "Amo o jeito carinhoso como você cuida de mim.",
    "Amo que você sempre presta atenção em cada detalhe.",
    "Amo como você me faz rir, mesmo nos dias difíceis.",
    "Amo sua paixão por rock e como me ensina a amar isso também.",
    "Amo seu cheiro, que fica marcado nos meus pensamentos.",
    "Amo sua sensibilidade e como percebe tudo ao seu redor.",
    "Amo o som da sua risada, que ilumina o meu dia.",
    "Amo a forma como você acredita em mim e me encoraja.",
    "Amo seu abraço que me faz sentir em casa.",
    "Amo como você transforma momentos simples em inesquecíveis.",
    "Amo o brilho dos seus olhos quando fala do que gosta.",
    "Amo escutar voce falar do que gosta.",
    "Amo o jeito como cuida de mim.",
    "Amo como vc inventa varios apelidos carinhosos.",
    "Amo seu jeito meigo de demonstrar amor em pequenas ações.",
    "Amo seu toque suave e reconfortante.",
    "Amo como você me entende sem precisar de palavras.",
    "Amo o fato de você me fazer uma pessoa melhor.",
    "Amo o jeito como cuida das pessoas que ama.",
    "Amo como se preocupa com o meu bem-estar.",
    "Amo como você torna cada dia especial.",
    "Amo o fato de que sempre posso contar com você.",
    "Amo seu jeito único de enxergar o mundo.",
    "Amo sua energia positiva e contagiante.",
    "Amo como compartilha seus sonhos comigo.",
    "Amo o jeito como me surpreende com pequenas coisas.",
    "Amo a paz que sinto quando estou ao seu lado.", 
/*    "Amo a sinceridade que traz para o nosso relacionamento.",
    "Amo o jeito que valoriza a nossa história juntos.",
    "Amo o calor do seu carinho que me faz sentir amado.",
    "Amo a forma como acredita no nosso futuro.",
    "Amo que você seja sempre autêntica e verdadeira.",
    "Amo o jeito como ilumina qualquer ambiente.",
    "Amo o amor que dedica ao que faz e aos que ama.",
    "Amo sua curiosidade e desejo de aprender sempre mais.",
    "Amo o jeito doce como fala comigo.",
    "Amo como respeita e valoriza meus sentimentos.",
    "Amo sua generosidade e disposição para ajudar os outros.",
    "Amo sua capacidade de ver o lado bom de cada situação.",
    "Amo que você me entende melhor do que eu mesmo.",
    "Amo como você traz tranquilidade aos meus dias.",
    "Amo a lealdade que demonstra em tudo que faz.",
    "Amo a forma como equilibra razão e emoção.",
    "Amo o jeito como compartilha os seus segredos comigo.",
    "Amo o jeito que me faz sentir especial todos os dias.",
    "Amo a forma como você cuida de nós e do nosso amor.",
    "Amo o jeito como você lida com os desafios.",
    "Amo seu sorriso, que ilumina até os dias nublados.",
    "Amo sua vontade de fazer o bem ao próximo.",
    "Amo sua paixão por descobrir coisas novas.",
    "Amo o jeito como me acolhe em seus braços.",
    "Amo como você me faz sentir completo.",
    "Amo a forma como sempre encontra o lado positivo.",
    "Amo seu jeito acolhedor de me ouvir e entender.",
    "Amo como você faz os meus dias mais leves.",
    "Amo que você sempre acredita no nosso amor.",
    "Amo o cuidado que tem com os nossos momentos juntos.",
    "Amo a sua espontaneidade e autenticidade.",
    "Amo o fato de você me fazer querer ser melhor.",
    "Amo a paz que sinto quando estou com você.",
    "Amo a maneira como você sempre vê o melhor em mim.",
    "Amo como você me incentiva a seguir meus sonhos.",
    "Amo sua sinceridade e transparência.",
    "Amo o jeito que faz eu me sentir seguro.",
    "Amo como você valoriza os pequenos momentos.",
    "Amo o som da sua voz que me acalma.",
    "Amo como você respeita minha individualidade.",
    "Amo o jeito que sempre me traz de volta ao foco.",
    "Amo que está sempre ao meu lado, não importa o que aconteça.",
    "Amo sua paciência e compreensão.",
    "Amo o brilho nos seus olhos quando estamos juntos.",
    "Amo a forma como valoriza cada detalhe nosso.",
    "Amo o apoio que você me dá nos meus sonhos.",
    "Amo como você torna tudo mais especial.",
    "Amo a forma como você me inspira todos os dias.",
    "Amo sua fé em nós, mesmo nas dificuldades.",
    "Amo o jeito que me faz sorrir sem motivo.",
    "Amo sua doçura e gentileza.",
    "Amo como você me faz sentir amado.",
    "Amo o fato de sempre me colocar para cima.",
    "Amo que você seja meu porto seguro.",
    "Amo como você me faz querer estar sempre perto.",
    "Amo sua força e determinação.",
    "Amo como você me acolhe com seu amor.",
    "Amo o jeito como valoriza nossa conexão.",
    "Amo o conforto que encontro em você.",
    "Amo como você me ensina a ver o mundo de outra forma.",
    "Amo o seu carinho que me preenche.",
    "Amo a parceria que construímos juntos.",
    "Amo a energia boa que me transmite.",
    "Amo como você se dedica ao nosso relacionamento.",
    "Amo o jeito como cuida de nós e do nosso futuro.",
    "Amo a segurança que encontro em você.",
    "Amo cada momento ao seu lado.",
    "Amo o jeito único que tem de demonstrar amor.",
    "Amo sua presença que me completa.",
    "Amo a nossa história e tudo o que ainda vamos viver.",
    "Amo a maneira como você ilumina o meu dia com um simples sorriso.",
    "Amo o jeito que você me inspira a ser uma pessoa melhor.",
    "Amo a forma como me entende mesmo quando eu não falo nada.",
    "Amo como você faz eu me sentir o único no mundo.",
    "Amo a sua inteligência e como compartilha seu conhecimento comigo.",
    "Amo o seu jeito de me acalmar quando estou nervoso.",
    "Amo como você faz cada momento ao seu lado ser único.",
    "Amo a sua dedicação em tudo o que faz.",
    "Amo como respeita meus sentimentos e minhas escolhas.",
    "Amo o jeito que você celebra cada uma de nossas conquistas.",
    "Amo como você me faz sentir completo.",
    "Amo seu olhar carinhoso que me faz sentir amado.",
    "Amo a sua empatia e como sempre pensa nos outros.",
    "Amo a sua risada contagiante que sempre me faz sorrir.",
    "Amo a paz que sinto quando estou ao seu lado.",
    "Amo a sua autenticidade e como é verdadeira consigo mesma.",
    "Amo o jeito que me incentiva a nunca desistir dos meus sonhos.",
    "Amo como você vê a beleza nas coisas mais simples.",
    "Amo o conforto que encontro quando estamos juntos.",
    "Amo como você faz eu me sentir seguro e em paz.",
    "Amo a leveza que traz aos meus dias.",
    "Amo o fato de que sempre posso contar com você.",
    "Amo o seu jeito encantador de lidar com as dificuldades.",
    "Amo como valoriza cada momento que passamos juntos.",
    "Amo o brilho no seu olhar quando estamos juntos.",
    "Amo a sua forma de me mostrar o quanto sou importante.",
    "Amo o seu abraço que parece curar tudo.",
    "Amo o jeito que se entrega ao nosso relacionamento.",
    "Amo o respeito que você tem por mim e por nossos sentimentos.",
    "Amo como consegue transformar o dia com uma simples palavra.",
    "Amo o jeito que me faz sentir especial a cada dia.",
    "Amo o cuidado que tem com as pessoas que ama.",
    "Amo a forma como me desafia a ser uma pessoa melhor.",
    "Amo o seu entusiasmo e paixão pela vida.",
    "Amo a forma como você apoia minhas decisões.",
    "Amo o fato de sempre querer o meu melhor.",
    "Amo o jeito como me faz sentir em casa, onde quer que estejamos.",
    "Amo a alegria que você traz para a minha vida.",
    "Amo como valoriza os nossos momentos a dois.",
    "Amo o carinho que me dá quando estou precisando.",
    "Amo a forma como você me faz rir até nos momentos mais difíceis.",
    "Amo a sua paciência em lidar com minhas falhas.",
    "Amo o seu toque suave que me acalma e conforta.",
    "Amo o jeito que respeita quem eu sou.",
    "Amo a maneira como celebra minhas vitórias como se fossem suas.",
    "Amo o seu apoio incondicional em todas as situações.",
    "Amo como você me mostra o lado bom de cada situação.",
    "Amo a confiança que você me transmite todos os dias.",
    "Amo a forma como você me olha com tanto amor.",
    "Amo o jeito que você se preocupa com meu bem-estar.",
    "Amo a gentileza com que trata todos ao seu redor.",
    "Amo como você faz eu me sentir amado com pequenos gestos.",
    "Amo a sua força e determinação.",
    "Amo como você consegue ver beleza em tudo.",
    "Amo a sua companhia, que faz qualquer momento ser especial.",
    "Amo a forma como celebra as nossas pequenas conquistas.",
    "Amo o seu senso de humor que sempre melhora meu dia.",
    "Amo o apoio que você me dá em tudo o que faço.",
    "Amo o seu jeito carinhoso de dizer que me ama.",
    "Amo como você valoriza nossa história.",
    "Amo como me faz acreditar que somos invencíveis juntos.",
    "Amo a serenidade que você traz para a minha vida.",
    "Amo o jeito como você lida com as minhas imperfeições.",
    "Amo a sua capacidade de me fazer sorrir em qualquer situação.",
    "Amo o respeito que você demonstra pelos nossos sentimentos.",
    "Amo como você faz com que eu me sinta importante.",
    "Amo a forma como valoriza cada detalhe nosso.",
    "Amo o apoio que você me dá mesmo quando erro.",
    "Amo o fato de me fazer sentir que sempre estará comigo.",
    "Amo como você me ajuda a ver a beleza nas coisas simples.",
    "Amo como você me faz sentir amado com um simples olhar.",
    "Amo o carinho que coloca em tudo o que faz.",
    "Amo o som da sua voz, que me traz paz.",
    "Amo como você me faz acreditar que o amor é para sempre.",
    "Amo a leveza que você traz ao meu coração.",
    "Amo como você se entrega ao nosso amor.",
    "Amo a sua coragem em enfrentar qualquer situação.",
    "Amo como você me dá forças para enfrentar o mundo.",
    "Amo como você me faz sentir especial com pequenos gestos.",
    "Amo o seu toque que me traz conforto e segurança.",
    "Amo a alegria que você traz para minha vida.",
    "Amo como você faz eu me sentir importante e amado.",
    "Amo a forma como vê o melhor em mim.",
    "Amo o fato de você me completar de todas as formas.",
    "Amo como você valoriza o que temos.",
    "Amo a forma como me respeita e aceita como sou.",
    "Amo a sensação de segurança que tenho ao seu lado.",
    "Amo como você me inspira a ser uma pessoa melhor.",
    "Amo o jeito como torna cada dia especial.",
    "Amo a forma como me olha, como se eu fosse tudo para você.",
    "Amo como me faz acreditar que juntos podemos tudo.",
    "Amo a forma como apoia meus sonhos e minhas escolhas.",
    "Amo o cuidado e carinho que me oferece a cada dia.",
    "Amo como valoriza a nossa felicidade acima de tudo.",
    "Amo a forma como nossa conexão é tão única.",
    "Amo o jeito que você me faz sentir amado sem esforço.",
    "Amo o fato de ser a melhor parte do meu dia.",
    "Amo como você faz com que eu acredite no amor verdadeiro.",
    "Amo como me traz tranquilidade só com sua presença.",
    "Amo o conforto que encontro em cada abraço seu.",
    "Amo o jeito como nossos corações batem em sintonia.",
    "Amo como você é tudo o que eu sempre sonhei.",
    "Amo como você sempre sabe o que dizer para me animar.",
    "Amo o jeito que valoriza os nossos momentos juntos.",
    "Amo como se preocupa com cada detalhe da nossa relação.",
    "Amo a confiança que transmite em cada gesto.",
    "Amo a maneira como nossos olhares se encontram.",
    "Amo como sempre coloca nossa felicidade em primeiro lugar.",
    "Amo como me faz querer ser uma pessoa melhor.",
    "Amo o jeito como me abraça e acalma minha alma.",
    "Amo sua paciência com minhas imperfeições.",
    "Amo como me ensina coisas novas todos os dias.",
    "Amo o seu otimismo e como me inspira.",
    "Amo o brilho nos seus olhos quando estamos juntos.",
    "Amo o carinho que coloca em cada mensagem.",
    "Amo como você é sempre honesta comigo.",
    "Amo o fato de sermos melhores juntos.",
    "Amo como valoriza cada conquista minha.",
    "Amo o seu jeito de transformar o cotidiano em aventura.",
    "Amo a sua dedicação a tudo o que faz.",
    "Amo como me lembra o quanto sou importante para você.",
    "Amo sua generosidade e como sempre pensa no próximo.",
    "Amo o fato de ser a primeira pessoa com quem quero falar.",
    "Amo o jeito que me faz sentir que sou seu mundo.",
    "Amo como compartilha comigo seus sonhos e medos.",
    "Amo o modo como se entrega ao nosso amor.",
    "Amo como me inspira a ser a melhor versão de mim.",
    "Amo a simplicidade com que me faz feliz.",
    "Amo como sempre faz eu me sentir valorizado.",
    "Amo o conforto de saber que posso contar com você.",
    "Amo a forma como você me incentiva a crescer.",
    "Amo a força que você me dá para encarar desafios.",
    "Amo a paz que encontro nos seus braços.",
    "Amo o fato de sempre saber o que estou sentindo.",
    "Amo o modo como nossos corações se completam.",
    "Amo a segurança que você traz para minha vida.",
    "Amo a cumplicidade que construímos juntos.",
    "Amo como você torna minha vida mais feliz.",
    "Amo o carinho que dedica a tudo o que fazemos.",
    "Amo como valoriza cada momento que passamos juntos.",
    "Amo o jeito que me faz acreditar no amor.",
    "Amo como me sinto protegido ao seu lado.",
    "Amo o jeito como nossas almas se entendem.",
    "Amo como me ajuda a superar meus medos.",
    "Amo o fato de você ser minha melhor amiga.",
    "Amo o jeito como lida com nossas diferenças.",
    "Amo como traz equilíbrio para minha vida.",
    "Amo a forma como cuida de cada detalhe.",
    "Amo o apoio que me dá em todas as decisões.",
    "Amo o som da sua voz que me acalma.",
    "Amo o jeito que valoriza nossa história.",
    "Amo o fato de ser sempre minha inspiração.",
    "Amo a confiança que deposita em mim.",
    "Amo a maneira como sempre traz alegria.",
    "Amo como você é única e especial.",
    "Amo o cuidado que tem com nossos sonhos.",
    "Amo como respeita quem eu sou.",
    "Amo o calor dos seus abraços.",
    "Amo o jeito que você me faz sorrir sem esforço.",
    "Amo a energia boa que traz para minha vida.",
    "Amo o carinho que coloca em cada palavra.",
    "Amo como faz tudo parecer mais fácil.",
    "Amo o jeito como encara a vida com coragem.",
    "Amo como ilumina até os dias mais difíceis.",
    "Amo a calma que você me traz.",
    "Amo como sempre me ouve com atenção.",
    "Amo o fato de ser a melhor parte do meu dia.",
    "Amo o carinho com que cuida de nós.",
    "Amo a forma como somos inseparáveis.",
    "Amo como você me faz acreditar em mim mesmo.",
    "Amo o jeito como nos completamos.",
    "Amo o respeito que tem por quem sou.",
    "Amo como me sinto inteiro ao seu lado.",
    "Amo a paz que sinto quando estamos juntos.",
    "Amo a forma como você valoriza nossas memórias.",
    "Amo o seu abraço que cura qualquer dor.",
    "Amo o fato de sempre acreditar no nosso amor.",
    "Amo como cada segundo ao seu lado é especial.",
    "Amo o jeito que sempre me faz sentir amado.",
    "Amo o carinho que dedica a tudo o que faz.",
    "Amo como você traz felicidade para a minha vida.",
    "Amo o fato de ser a razão do meu sorriso.",
    "Amo a lealdade que demonstra em nosso amor.",
    "Amo o jeito que me acalma nos momentos difíceis.",
    "Amo a forma como acredita no nosso futuro.",
    "Amo como cuida do nosso amor todos os dias.",
    "Amo o conforto que encontro em cada abraço.",
    "Amo a segurança que sinto ao seu lado.",
    "Amo o jeito que faz a vida ser mais doce.",
    "Amo como enxerga o melhor em mim.",
    "Amo a confiança que tem em nosso amor.",
    "Amo o calor que sinto com a sua presença.",
    "Amo o cuidado que tem comigo e com nosso amor.",
    "Amo o jeito como me faz sentir em paz.",
    "Amo como você sempre está ao meu lado.",
    "Amo o fato de sempre tornar meus dias melhores.",
    "Amo como me faz querer ser uma pessoa melhor.",
    "Amo a alegria que sinto quando estamos juntos.",
    "Amo como nossa conexão é tão especial.",
    "Amo a paciência que tem comigo.",
    "Amo a sinceridade do seu amor por mim.",
    "Amo como me faz ver o lado bom de tudo.",
    "Amo o jeito que valoriza cada segundo ao meu lado.",
    "Amo o fato de que sempre me apoia.",
    "Amo a maneira como lida com minhas inseguranças.",
    "Amo como me faz sentir importante e amado.",
    "Amo o carinho que coloca em nosso amor.",
    "Amo a paz que sinto só em estar ao seu lado.",
    "Amo como você torna tudo mais bonito.",
    "Amo o seu jeito de me motivar nos dias difíceis.",
    "Amo como você me faz sentir amado de verdade.",
    "Amo sua risada, que ilumina qualquer ambiente.",
    "Amo a paz que você traz para minha vida.",
    "Amo a leveza que sinto ao seu lado.",
    "Amo como você cuida dos nossos sonhos.",
    "Amo seu carinho, que é sempre genuíno.",
    "Amo a forma como valoriza nosso tempo juntos.",
    "Amo a conexão única que temos.",
    "Amo a bondade que existe no seu coração.",
    "Amo o jeito como me faz acreditar no amor todos os dias.",
    "Amo o brilho nos seus olhos quando falamos de futuro.",
    "Amo como você transforma a vida em algo maravilhoso.",
    "Amo a segurança que sinto ao seu lado.",
    "Amo como você torna tudo mais fácil.",
    "Amo como você enxerga o melhor em mim.",
    "Amo a maneira como compartilha seus sonhos comigo.",
    "Amo como você é minha melhor amiga e amor ao mesmo tempo.",
    "Amo como você torna qualquer lugar em lar.",
    "Amo sua energia positiva, que me contagia.",
    "Amo como você me faz querer ser alguém melhor.",
    "Amo a gentileza e a delicadeza do seu coração.",
    "Amo a força que você tem para enfrentar tudo.",
    "Amo como você está sempre ao meu lado.",
    "Amo o carinho que sinto só de segurar sua mão.",
    "Amo a forma como lida com nossos desafios.",
    "Amo como você sempre me coloca para cima.",
    "Amo o jeito que me olha, cheio de amor.",
    "Amo como me faz sentir a pessoa mais especial do mundo.",
    "Amo a calma que você traz para minha alma.",
    "Amo o seu apoio constante e verdadeiro.",
    "Amo como você faz os dias nublados parecerem claros.",
    "Amo como seu toque me transmite paz.",
    "Amo a segurança que sinto só de saber que tenho você.",
    "Amo como compartilha comigo suas paixões.",
    "Amo a tranquilidade que sinto quando estamos juntos.",
    "Amo como você vê o melhor em todas as pessoas.",
    "Amo o amor que você dedica a tudo que faz.",
    "Amo o jeito que me escuta e me entende.",
    "Amo como você valoriza cada conquista nossa.",
    "Amo como você torna o mundo mais bonito.",
    "Amo sua sinceridade, que me faz confiar ainda mais.",
    "Amo o aconchego que sinto só de te abraçar.",
    "Amo como você me faz sentir amado e protegido.",
    "Amo a sua positividade e como vê o mundo.",
    "Amo como transforma os pequenos momentos em grandes memórias.",
    "Amo a sua lealdade e dedicação ao nosso amor.",
    "Amo o seu jeito único e especial.",
    "Amo como me faz sentir completo e amado.",
    "Amo o seu jeito de lidar com a vida e com as pessoas.",
    "Amo o amor e o respeito que temos um pelo outro.",
    "Amo a ternura que sinto em cada gesto seu.",
    "Amo como você me incentiva a ser o melhor de mim.",
    "Amo o brilho nos seus olhos quando sorri.",
    "Amo como me faz acreditar que o amor é eterno.",
    "Amo o jeito que me faz sentir em casa.",
    "Amo a segurança que você traz para minha vida.",
    "Amo o carinho que vejo em cada ato seu.",
    "Amo o apoio que me dá em todas as situações.",
    "Amo como sempre me surpreende com gestos de amor.",
    "Amo a cumplicidade que existe entre nós.",
    "Amo o jeito como cuida de mim.",
    "Amo o amor que vejo em cada sorriso seu.",
    "Amo como compartilha sua vida comigo.",
    "Amo o jeito como me faz ver a beleza em tudo.",
    "Amo como é sempre sincera comigo.",
    "Amo o fato de ser meu amor e meu melhor apoio." */
];


// Calcular a mensagem do dia
const today = new Date();
const dayOfYear = Math.floor((today - new Date(today.getFullYear(), 0, 0)) / 1000 / 60 / 60 / 24);
const mensagemIndex = dayOfYear % mensagens.length;
document.getElementById("mensagem").innerText = mensagens[mensagemIndex];

// Calcular o contador de dias de namoro
const dataInicio = new Date('2024-10-17');
const diasNamorando = Math.floor((today - dataInicio) / (1000 * 60 * 60 * 24));
document.getElementById("dias-namorando").innerText = `Estamos namorando há ${diasNamorando} dias.`;
