const mensagens = [
    "Amo o jeito carinhoso como você cuida de mim.",
    "Amo que você sempre presta atenção em cada detalhe.",
    "Amo como você me faz rir, mesmo nos dias difíceis.",
    "Amo sua paixão por rock e como me ensina a amar isso também.",
    "Amo seu cheiro, que fica marcado nos meus pensamentos.",
    "Amo seus olhos e como eles brilham ao me ver.",
    "Amo seu sorriso e como ele alegra o ambiente.",
    "Amo a forma como você acredita em mim e me encoraja.",
    "Amo seu abraço que me faz sentir em casa.",
    "Amo como você transforma momentos simples em inesquecíveis.",
    "Amo o brilho dos seus olhos quando fala do que gosta.",
    "Amo escutar voce falar do que gosta.",
    "Amo o jeito como cuida de mim.",
    "Amo como vc inventa varios apelidos carinhosos.",
    "Amo seu jeito meigo de demonstrar amor em pequenas ações.",
    "Amo seu toque suave e reconfortante.",
    "Amo como você me entende sem precisar de palavras.",
    "Amo o fato de você me fazer uma pessoa melhor.",
    "Amo o jeito como cuida das pessoas que ama.",
    "Amo como se preocupa com o meu bem-estar.",
    "Amo como você torna cada dia especial.",
    "Amo o fato de que sempre posso contar com você.",
    "Amo seu jeito único de enxergar o mundo.",
    "Amo nossos RPs.",
    "Amo como compartilha seus sonhos comigo.",
    "Amo cozinhar com voce.",
    "Amo passar horas deitado ao seu lado.", 
    "Amo nossas vigens em nossos pensamentos.",
    "Amo seus beijos e como eles me alegram.",
    "Amo o calor do seu carinho que me faz sentir amado.",
    "Amo todos os seus abraços.",
    "Amo sua sinceridade.",
    "Amo quando voce me olha com um olhar de desejo.",
    "Amo passear com voce.",
    "Amo como voce presta atençao quando estou falando besteira.",
    "Amo o jeito doce como fala comigo.",
    "Amo quando voce me chama de minha vida.",
    "Amo chamar voce de minha vida.",
    "Amo sua paciencia em lidar comigo.",
    "Amo que você me entende melhor do que eu mesmo.",
    "Amo como você traz a paz para os meus dias.",
    "Amo a lealdade que demonstra em tudo que faz.",
    "Amo a forma como equilibra razão e emoção.",
    "Amo o jeito como compartilha os seus segredos comigo.",
    "Amo o quanto vc é sincera comigo.",
    "Amo o jeito que me faz sentir especial todos os dias.",
    "Amo a forma como você cuida de nós e do nosso amor.",
    "Amo passar os dias ao seu lado.",
    "Amo seu lindo sorriso.",
    "Amo quando você me tira um sorriso.",
    "Amo sua paixão por ficção científica.",
    "Amo o jeito como me acolhe em seus braços.",
    "Amo como você me faz sentir completo.",
    "Amo o seu lado seria.",
    "Amo seu jeito descontraído e divertido.",
    "Amo como você faz os meus dias mais leves.",
    "Amo quando você pergunta 'você sabia?'.",
    "Amo ser seu momolado.",
    "Amo o fato de você ser minha momolada.",
    "Amo quando você cuida de mim.",
    "Amo a paz que sinto quando estou com você.",
    "Amo nossas brincadeiras.",
    "Amo observar seu olhar apaixonado.",
    "Amo sua comida (olhinhos).",
    "Amo dormir ao seu lado.",
    "Amo como você valoriza os pequenos momentos.",
    "Amo o som da sua voz.",
    "Amo como você me respeita.",
    "Amo suas loucuras.",
    "Amo seu estilo.",
    "Amo quando voce me da banho.",
    "Amo o brilho nos seus olhos.",
    "Amo a forma percebe pequenos detalhes.",
    "Amo o apoio que você me da.",
    "Amo como você torna tudo mais especial.",
    "Amo a forma como você me inspira todos os dias.",
    "Amo sua carinha seria.",
    "Amo como você quer fazer meus desejos.",
    "Amo o fato de n termos segredos.",
    "Amo como você não consegue esconder segredos de mim.",
    "Amo o fato de sempre me animar.",
    "Amo que você seja meu porto seguro.",
    "Amo como você me faz querer estar sempre perto.",
    "Amo como você sempre me quer por perto.",
    "Amo quando colocamos nossos oculos juntinhos.",
    "Amo cozinhar ao seu lado.",
    "Amo ser sua conchinha maior.",
    "Amo ser a sua conchinha menor.",
    "Amo o seu carinho que me preenche.",
    "Amo a sua parceria.",
    "Amo quando você cria teorias loucas.",
    "Amo como você se dedica ao nosso relacionamento.",
    "Amo quando nos pensamos em nosso futuro.",
    "Amo a segurança que você me da.",
    "Amo cada momento ao seu lado.",
    "Amo almoçar ao seu lado.",
    "Amo o fato de você pegar meus costumes.",
    "Amo lembrar de nossas histórias e rir.",
    "Amo os momentos que você pula de animação.",
    "Amo mostrar a bunda para você.",
    "Amo a forma como me entende mesmo quando eu não falo nada.",
    "Amo como você cuida de mim enquanto durmo.",
    "Amo todo o seu conhecimento aleatório.",
    "Amo sua cara quando vem me dizer algo e digo que ja sabia.",
    "Amo todo o cuidado que você tem comigo.",
    "Amo todas as pequenas coisas que você faz por mim.",
    "Amo quando diz -isso me lembrou você-.",
    "Amo fazer pequenas coisas por você.",
    "Amo como você me faz sentir completo.",
    "Amo seu olhar carinhoso que me faz sentir amado.",
    "Amo fazer brincadeiras com você.",
    "Amo saber que você sempre vai estar do meu lado.",
    "Amo a paz que sinto quando estou ao seu lado.",
    "Amo fazer coizinhas de casais com você.",
    "Amo como sempre quer me deixar o mais confortável possivel.",
    "Amo nosso sexo.",
    "Amo o conforto que encontro quando estamos juntos.",
    "Amo seus piercing, eles são lindos.",
    "Amo todos os nosso beijos.",
    "Amo o fato de que sempre posso contar com você.",
    "Amo todas as suas historias.",
    "Amo como valoriza cada momento que passamos juntos.",
    "Amo o brilho no seu olhar quando estamos juntos.",
    "Amo a sua forma de me mostrar o quanto sou importante.",
    "Amo o calor dos seus abraços.",
    "Amo o jeito de como se preoculpa comigo.",
    "Amo nossas brincadeiras na hora do banho.",
    "Amo como a cada dia vc vem se sentindo mais a vontade comigo.",
    "Amo o jeito que me faz sentir especial a cada dia.",
    "Amo a atenção que você tem com a minha hidratação.",
    "Amo jogar com você.",
    "Amo poder cuidar de você.",
    "Amo a forma como você apoia minhas decisões.",
    "Amo o fato de sempre querer o meu melhor.",
    "Amo o jeito como me faz sentir em casa.",
    "Amo a alegria que você traz para a minha vida.",
    "Amo todos os nossos momentos a dois.",
    "Amo o carinho que me dá quando estou precisando.",
    "Amo a forma como você me faz rir.",
    "Amo seus cafunés.",
    "Amo a segurança que vc me passa ao dormir do seu lado.",
    "Amo o jeito que respeita quem eu sou.",
    "Amo a maneira como celebra minhas vitórias como se fossem suas.",
    "Amo o fato que querer saber tudo sobre meu dia.",
    "Amo todos os seus presentes.",
    "Amo a confiança que você tem em mim.",
    "Amo a forma como você me olha com tanto amor.",
    "Amo o jeito que você se preocupa com meu bem-estar.",
    "Amo como tens paciencia de ler 365 motivos.",
    "Amo como você faz eu me sentir amado com pequenos gestos.",
    "Amo a sua força.",
    "Amo nossos assuntos viajados.",
    "Amo a sua companhia, que faz qualquer momento ser especial.",
    "Amo seus coturnos (ja olhou eles hj?).",
    "Amo a forma como celebra as nossas pequenas conquistas.",
    "Amo chegar em casa e ter você para me acolher.",
    "Amo como tenta me fazer feliz todos os dias.",
    "Amo assistir seus filmes preferidos.",
    "Amo assistir suas series preferidas.",
    "Amo o brilho em seus olhos quando esta ouvindo o que gosta.",
    "Amo como em meio ao caos vc me traz serenidade.",
    "Amo o jeito como você lida com as minhas imperfeições.",
    "Amo a sua capacidade de me fazer sorrir em qualquer situação.",
    "Amo o respeito que você demonstra pelos nossos sentimentos.",
    "Amo como você faz com que eu me sinta importante.",
    "Amo a forma como valoriza cada detalhe nosso.",
    "Amo o apoio que você me dá mesmo quando erro.",
    "Amo como você sempre tenta melhorar.",
    "Amo como você pensa em mim em momentos dificeis.",
    "Amo como você me faz sentir amado com um simples olhar.",
    "Amo o fato de você sempre querer estar ao meu lado.",
    "Amo o som da sua voz, que me traz paz.",
    "Amo como você me faz acreditar que o amor é para sempre.",
    "Amo a leveza que você traz ao meu coração.",
    "Amo a intensidade que você traz ao meu coração.",
    "Amo a sua coragem em enfrentar qualquer situação.",
    "Amo como você me dá forças para enfrentar o mundo.",
    "Amo lutar pelo nosso amor.",
    "Amo o seu toque que me traz conforto e segurança.",
    "Amo a alegria que você traz para minha vida.",
    "Amo como você faz eu me sentir importante e amado.",
    "Amo a forma como vê o melhor em mim.",
    "Amo o fato de você me completar de todas as formas.",
    "Amo como você valoriza o que temos.",
    "Amo o fato de sermos diferentes.",
    "Amo o os detalhes em que somos iguais.",
    "Amo como você inspira o meu melhor.",
    "Amo o jeito como torna cada dia especial.",
    "Amo a forma como me olha, como se eu fosse tudo para você.",
    "Amo como me faz acreditar que juntos podemos tudo.",
    "Amo a forma como apoia meus sonhos e minhas escolhas.",
    "Amo seus cuidados e carinhos.",
    "Amo como valoriza a nossa felicidade acima de tudo.",
    "Amo como esta disposta a se sacrificar pela gente.",
    "Amo o jeito que você me faz sentir amado sem esforço.",
    "Amo o fato de ser a melhor parte do meu dia.",
    "Amo todas as suas mensagens.",
    "Amo a energia que nosso amor trasmite.",
    "Amo o conforto que encontro em cada abraço seu.",
    "Amo o jeito como nossos corações batem em sintonia.",
    "Amo como você é tudo o que eu sempre sonhei (e mais um pouco).",
    "Amo como você sempre se dedica para me animar.",
    "Amo o jeito que valoriza os nossos momentos juntos.",
    "Amo como se preocupa com cada detalhe da nossa relação.",
    "Amo a sua preocupação com nossas datas.",
    "Amo a maneira como nossos olhares se encontram.",
    "Amo encarar seu rosto e observar como ele é lindo.",
    "Amo tomar banho com você.",
    "Amo cozinhar com você.",
    "Amo ler com você.",
    "Amo beijar você.",
    "Amo dedicar meu tempo a nos.",
    "Amo o brilho nos seus olhos quando estamos juntos.",
    "Amo o carinho que coloca em cada mensagem.",
    "Amo como você é sempre honesta comigo.",
    "Amo o fato de você nunca mentir para mim.",
    "Amo como você sempre que fazer coisas novas.",
    "Amo sua criatividade.",
    "Amo rodos os nossos RPs.",
    "Amo como me lembra o quanto sou importante para você.",
    "Amo como você sempre é graciosa.",
    "Amo o fato de ser a primeira pessoa com quem quero falar.",
    "Amo o jeito que me faz sentir que sou seu mundo.",
    "Amo o fato de que você se trasformou no meu mundo.",
    "Amo o modo como se entrega ao nosso amor.",
    "Amo como me inspira a ser a melhor versão de mim.",
    "Amo a simplicidade com que me faz feliz.",
/*  "Amo como sempre faz eu me sentir valorizado.",
    "Amo o conforto de saber que posso contar com você.",
    "Amo a forma como você me incentiva a crescer.",
    "Amo a força que você me dá para encarar desafios.",
    "Amo a paz que encontro nos seus braços.",
    "Amo o fato de sempre saber o que estou sentindo.",
    "Amo o modo como nossos corações se completam.",
    "Amo a segurança que você traz para minha vida.",
    "Amo a cumplicidade que construímos juntos.",
    "Amo como você torna minha vida mais feliz.",
    "Amo o carinho que dedica a tudo o que fazemos.",
    "Amo como valoriza cada momento que passamos juntos.",
    "Amo o jeito que me faz acreditar no amor.",
    "Amo como me sinto protegido ao seu lado.",
    "Amo o jeito como nossas almas se entendem.",
    "Amo como me ajuda a superar meus medos.",
    "Amo o fato de você ser minha melhor amiga.",
    "Amo o jeito como lida com nossas diferenças.",
    "Amo como traz equilíbrio para minha vida.",
    "Amo a forma como cuida de cada detalhe.",
    "Amo o apoio que me dá em todas as decisões.",
    "Amo o som da sua voz que me acalma.",
    "Amo o jeito que valoriza nossa história.",
    "Amo o fato de ser sempre minha inspiração.",
    "Amo a confiança que deposita em mim.",
    "Amo a maneira como sempre traz alegria.",
    "Amo como você é única e especial.",
    "Amo o cuidado que tem com nossos sonhos.",
    "Amo como respeita quem eu sou.",
    "Amo o calor dos seus abraços.",
    "Amo o jeito que você me faz sorrir sem esforço.",
    "Amo a energia boa que traz para minha vida.",
    "Amo o carinho que coloca em cada palavra.",
    "Amo como faz tudo parecer mais fácil.",
    "Amo o jeito como encara a vida com coragem.",
    "Amo como ilumina até os dias mais difíceis.",
    "Amo a calma que você me traz.",
    "Amo como sempre me ouve com atenção.",
    "Amo o fato de ser a melhor parte do meu dia.",
    "Amo o carinho com que cuida de nós.",
    "Amo a forma como somos inseparáveis.",
    "Amo como você me faz acreditar em mim mesmo.",
    "Amo o jeito como nos completamos.",
    "Amo o respeito que tem por quem sou.",
    "Amo como me sinto inteiro ao seu lado.",
    "Amo a paz que sinto quando estamos juntos.",
    "Amo a forma como você valoriza nossas memórias.",
    "Amo o seu abraço que cura qualquer dor.",
    "Amo o fato de sempre acreditar no nosso amor.",
    "Amo como cada segundo ao seu lado é especial.",
    "Amo o jeito que sempre me faz sentir amado.",
    "Amo o carinho que dedica a tudo o que faz.",
    "Amo como você traz felicidade para a minha vida.",
    "Amo o fato de ser a razão do meu sorriso.",
    "Amo a lealdade que demonstra em nosso amor.",
    "Amo o jeito que me acalma nos momentos difíceis.",
    "Amo a forma como acredita no nosso futuro.",
    "Amo como cuida do nosso amor todos os dias.",
    "Amo o conforto que encontro em cada abraço.",
    "Amo a segurança que sinto ao seu lado.",
    "Amo o jeito que faz a vida ser mais doce.",
    "Amo como enxerga o melhor em mim.",
    "Amo a confiança que tem em nosso amor.",
    "Amo o calor que sinto com a sua presença.",
    "Amo o cuidado que tem comigo e com nosso amor.",
    "Amo o jeito como me faz sentir em paz.",
    "Amo como você sempre está ao meu lado.",
    "Amo o fato de sempre tornar meus dias melhores.",
    "Amo como me faz querer ser uma pessoa melhor.",
    "Amo a alegria que sinto quando estamos juntos.",
    "Amo como nossa conexão é tão especial.",
    "Amo a paciência que tem comigo.",
    "Amo a sinceridade do seu amor por mim.",
    "Amo como me faz ver o lado bom de tudo.",
    "Amo o jeito que valoriza cada segundo ao meu lado.",
    "Amo o fato de que sempre me apoia.",
    "Amo a maneira como lida com minhas inseguranças.",
    "Amo como me faz sentir importante e amado.",
    "Amo o carinho que coloca em nosso amor.",
    "Amo a paz que sinto só em estar ao seu lado.",
    "Amo como você torna tudo mais bonito.",
    "Amo o seu jeito de me motivar nos dias difíceis.",
    "Amo como você me faz sentir amado de verdade.",
    "Amo sua risada, que ilumina qualquer ambiente.",
    "Amo a paz que você traz para minha vida.",
    "Amo a leveza que sinto ao seu lado.",
    "Amo como você cuida dos nossos sonhos.",
    "Amo seu carinho, que é sempre genuíno.",
    "Amo a forma como valoriza nosso tempo juntos.",
    "Amo a conexão única que temos.",
    "Amo a bondade que existe no seu coração.",
    "Amo o jeito como me faz acreditar no amor todos os dias.",
    "Amo o brilho nos seus olhos quando falamos de futuro.",
    "Amo como você transforma a vida em algo maravilhoso.",
    "Amo a segurança que sinto ao seu lado.",
    "Amo como você torna tudo mais fácil.",
    "Amo como você enxerga o melhor em mim.",
    "Amo a maneira como compartilha seus sonhos comigo.",
    "Amo como você é minha melhor amiga e amor ao mesmo tempo.",
    "Amo como você torna qualquer lugar em lar.",
    "Amo sua energia positiva, que me contagia.",
    "Amo como você me faz querer ser alguém melhor.",
    "Amo a gentileza e a delicadeza do seu coração.",
    "Amo a força que você tem para enfrentar tudo.",
    "Amo como você está sempre ao meu lado.",
    "Amo o carinho que sinto só de segurar sua mão.",
    "Amo a forma como lida com nossos desafios.",
    "Amo como você sempre me coloca para cima.",
    "Amo o jeito que me olha, cheio de amor.",
    "Amo como me faz sentir a pessoa mais especial do mundo.",
    "Amo a calma que você traz para minha alma.",
    "Amo o seu apoio constante e verdadeiro.",
    "Amo como você faz os dias nublados parecerem claros.",
    "Amo como seu toque me transmite paz.",
    "Amo a segurança que sinto só de saber que tenho você.",
    "Amo como compartilha comigo suas paixões.",
    "Amo a tranquilidade que sinto quando estamos juntos.",
    "Amo como você vê o melhor em todas as pessoas.",
    "Amo o amor que você dedica a tudo que faz.",
    "Amo o jeito que me escuta e me entende.",
    "Amo como você valoriza cada conquista nossa.",
    "Amo como você torna o mundo mais bonito.",
    "Amo sua sinceridade, que me faz confiar ainda mais.",
    "Amo o aconchego que sinto só de te abraçar.",
    "Amo como você me faz sentir amado e protegido.",
    "Amo a sua positividade e como vê o mundo.",
    "Amo como transforma os pequenos momentos em grandes memórias.",
    "Amo a sua lealdade e dedicação ao nosso amor.",
    "Amo o seu jeito único e especial.",
    "Amo como me faz sentir completo e amado.",
    "Amo o seu jeito de lidar com a vida e com as pessoas.",
    "Amo o amor e o respeito que temos um pelo outro.",
    "Amo a ternura que sinto em cada gesto seu.",
    "Amo como você me incentiva a ser o melhor de mim.",
    "Amo o brilho nos seus olhos quando sorri.",
    "Amo como me faz acreditar que o amor é eterno.",
    "Amo o jeito que me faz sentir em casa.",
    "Amo a segurança que você traz para minha vida.",
    "Amo o carinho que vejo em cada ato seu.",
    "Amo o apoio que me dá em todas as situações.",
    "Amo como sempre me surpreende com gestos de amor.",
    "Amo a cumplicidade que existe entre nós.",
    "Amo o jeito como cuida de mim.",
    "Amo o amor que vejo em cada sorriso seu.",
    "Amo como compartilha sua vida comigo.",
    "Amo o jeito como me faz ver a beleza em tudo.",
    "Amo como é sempre sincera comigo.",
    "Amo o fato de ser meu amor e meu melhor apoio." */
];

//----------------------------------------------

// Calcular a mensagem do dia
const today = new Date();
const dataInicio = new Date('2024-10-17');
const diasNamorando = Math.floor((today - dataInicio) / (1000 * 60 * 60 * 24));
const detalhesNamorando = Math.floor(today - dataInicio);
document.getElementById("mensagem").innerText = mensagens[diasNamorando - 1];
document.getElementById("dias-namorando").innerText = `Estamos namorando há ${diasNamorando} dias.`;
//document.getElementById("detalhes-namorando").innerText = `Estamos namorando há ${((detalhesNamorando)/1000*60*60)} segundos.`;

// Selecionar apenas as primeiras mensagens
const mensagensLimitadas = mensagens.slice(0, diasNamorando);

// Exibindo as mensagens no HTML
const listaMensagens = document.getElementById("lista_mensagens");
mensagensLimitadas.forEach((mensagem) => {
    const li = document.createElement("li");
    li.textContent = mensagem;
    listaMensagens.appendChild(li);

});

// Alternar visibilidade da lista
const botaoToggle = document.getElementById("toggle_lista");
botaoToggle.addEventListener("click", () => {
    if (listaMensagens.style.display === "none") {
        listaMensagens.style.display = "block";
        botaoToggle.textContent = "Exibir todas as mensagens *BETA*";
    } else {
        listaMensagens.style.display = "none";
        botaoToggle.textContent = "Exibir todas as mensagens *BETA*";
    }
});

const botaovoltar = document.getElementById("voltar_lista");
botaovoltar.addEventListener("click", () => {
    if (listaMensagens.style.display === "none") {
        listaMensagens.style.display = "block";
        botaovoltar.textContent = "voltar";
    } else {
        listaMensagens.style.display = "none";
        botaovoltar.textContent = "voltar";
    }
});
